[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "SploitScan"
version = "0.8.0"
description = "SploitScan is a sophisticated cybersecurity utility designed to provide detailed information on vulnerabilities and associated exploits."
authors = ["Alexander Hagenah <ah@primepage.de>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.urls]
homepage = "https://github.com/xaitax/SploitScan"
repository = "https://github.com/xaitax/SploitScan"
documentation = "https://github.com/xaitax/SploitScan#readme"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
jinja2 = "^3.1.2"
