[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "SploitScan"
version = "0.5.0"
description = "A tool to fetch and display data from NVD and public exploits for given CVE IDs."
authors = ["Alexander Hagenah <ah@primepage.de>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.urls]
homepage = "https://github.com/xaitax/SploitScan"
repository = "https://github.com/xaitax/SploitScan"
documentation = "https://github.com/xaitax/SploitScan#readme"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
tabulate = "^0.9.0"
